/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthNewQuotationLayoutRouteRouteImport } from './routes/_auth/newQuotationLayout/route'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthNewQuotationLayoutVehicleStepIndexRouteImport } from './routes/_auth/newQuotationLayout/vehicleStep/index'
import { Route as AuthNewQuotationLayoutValidationStepIndexRouteImport } from './routes/_auth/newQuotationLayout/validationStep/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNewQuotationLayoutRouteRoute =
  AuthNewQuotationLayoutRouteRouteImport.update({
    id: '/newQuotationLayout',
    path: '/newQuotationLayout',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewQuotationLayoutVehicleStepIndexRoute =
  AuthNewQuotationLayoutVehicleStepIndexRouteImport.update({
    id: '/vehicleStep/',
    path: '/vehicleStep/',
    getParentRoute: () => AuthNewQuotationLayoutRouteRoute,
  } as any)
const AuthNewQuotationLayoutValidationStepIndexRoute =
  AuthNewQuotationLayoutValidationStepIndexRouteImport.update({
    id: '/validationStep/',
    path: '/validationStep/',
    getParentRoute: () => AuthNewQuotationLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/newQuotationLayout': typeof AuthNewQuotationLayoutRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/newQuotationLayout/validationStep': typeof AuthNewQuotationLayoutValidationStepIndexRoute
  '/newQuotationLayout/vehicleStep': typeof AuthNewQuotationLayoutVehicleStepIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/newQuotationLayout': typeof AuthNewQuotationLayoutRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/newQuotationLayout/validationStep': typeof AuthNewQuotationLayoutValidationStepIndexRoute
  '/newQuotationLayout/vehicleStep': typeof AuthNewQuotationLayoutVehicleStepIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/newQuotationLayout': typeof AuthNewQuotationLayoutRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/newQuotationLayout/validationStep/': typeof AuthNewQuotationLayoutValidationStepIndexRoute
  '/_auth/newQuotationLayout/vehicleStep/': typeof AuthNewQuotationLayoutVehicleStepIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/newQuotationLayout'
    | '/login'
    | '/dashboard'
    | '/newQuotationLayout/validationStep'
    | '/newQuotationLayout/vehicleStep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/newQuotationLayout'
    | '/login'
    | '/dashboard'
    | '/newQuotationLayout/validationStep'
    | '/newQuotationLayout/vehicleStep'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/newQuotationLayout'
    | '/login/'
    | '/_auth/dashboard/'
    | '/_auth/newQuotationLayout/validationStep/'
    | '/_auth/newQuotationLayout/vehicleStep/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/newQuotationLayout': {
      id: '/_auth/newQuotationLayout'
      path: '/newQuotationLayout'
      fullPath: '/newQuotationLayout'
      preLoaderRoute: typeof AuthNewQuotationLayoutRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/newQuotationLayout/vehicleStep/': {
      id: '/_auth/newQuotationLayout/vehicleStep/'
      path: '/vehicleStep'
      fullPath: '/newQuotationLayout/vehicleStep'
      preLoaderRoute: typeof AuthNewQuotationLayoutVehicleStepIndexRouteImport
      parentRoute: typeof AuthNewQuotationLayoutRouteRoute
    }
    '/_auth/newQuotationLayout/validationStep/': {
      id: '/_auth/newQuotationLayout/validationStep/'
      path: '/validationStep'
      fullPath: '/newQuotationLayout/validationStep'
      preLoaderRoute: typeof AuthNewQuotationLayoutValidationStepIndexRouteImport
      parentRoute: typeof AuthNewQuotationLayoutRouteRoute
    }
  }
}

interface AuthNewQuotationLayoutRouteRouteChildren {
  AuthNewQuotationLayoutValidationStepIndexRoute: typeof AuthNewQuotationLayoutValidationStepIndexRoute
  AuthNewQuotationLayoutVehicleStepIndexRoute: typeof AuthNewQuotationLayoutVehicleStepIndexRoute
}

const AuthNewQuotationLayoutRouteRouteChildren: AuthNewQuotationLayoutRouteRouteChildren =
  {
    AuthNewQuotationLayoutValidationStepIndexRoute:
      AuthNewQuotationLayoutValidationStepIndexRoute,
    AuthNewQuotationLayoutVehicleStepIndexRoute:
      AuthNewQuotationLayoutVehicleStepIndexRoute,
  }

const AuthNewQuotationLayoutRouteRouteWithChildren =
  AuthNewQuotationLayoutRouteRoute._addFileChildren(
    AuthNewQuotationLayoutRouteRouteChildren,
  )

interface AuthRouteChildren {
  AuthNewQuotationLayoutRouteRoute: typeof AuthNewQuotationLayoutRouteRouteWithChildren
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthNewQuotationLayoutRouteRoute:
    AuthNewQuotationLayoutRouteRouteWithChildren,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
